export const Workshop = [
  {
    agence: '360° voyage-events',
    prenom: 'Caroline',
    nom: 'Démas',
    groupe: 'Groupe 1',
  },
  {
    agence: 'Adenium Conseil',
    prenom: 'Edwige',
    nom: 'Patin',
    groupe: 'Groupe 1',
  },
  {
    agence: 'Ailurus Fulgens Events',
    prenom: 'Ségolène',
    nom: 'De Gouzillon de Belizal',
    groupe: 'Groupe 1',
  },
  {
    agence: 'Alliance Meeting',
    prenom: 'Franck',
    nom: 'Franchitto',
    groupe: 'Groupe 2',
  },
  {
    agence: 'Amedida',
    prenom: 'Laetitia',
    nom: 'Teixeira',
    groupe: 'Groupe 2',
  },
  { agence: 'Amedida', prenom: 'Marie', nom: 'Lechat', groupe: 'Groupe 3' },
  { agence: 'Azoka', prenom: 'Sigolène', nom: 'Mathieu', groupe: 'Groupe 2' },
  { agence: 'BMA', prenom: 'Chantal', nom: 'Clapeau', groupe: 'Groupe 2' },
  {
    agence: 'Business Trotter',
    prenom: 'Nathalie',
    nom: 'Lizeau',
    groupe: 'Groupe 3',
  },
  { agence: 'Cap 5', prenom: 'Olivier', nom: 'Six', groupe: 'Groupe 3' },
  { agence: 'Contrastes', prenom: 'Joy', nom: 'Girbig', groupe: 'Groupe 3' },
  {
    agence: 'Creative Events',
    prenom: 'Géraldine',
    nom: 'Gandais',
    groupe: 'Groupe 4',
  },
  {
    agence: "D'Calé",
    prenom: 'Dolorès',
    nom: 'Thibaudeau',
    groupe: 'Groupe 4',
  },
  {
    agence: 'Destination Plus',
    prenom: 'Caroline',
    nom: 'Kutner',
    groupe: 'Groupe 4',
  },
  {
    agence: 'Destination Plus',
    prenom: 'Nadia',
    nom: 'Marzougui',
    groupe: 'Groupe 5',
  },
  {
    agence: 'Destinations Conseils',
    prenom: 'Nicolas',
    nom: 'Michau',
    groupe: 'Groupe 5',
  },
  { agence: 'Egg', prenom: 'Stéphanie', nom: 'Houel', groupe: 'Groupe 5' },
  { agence: 'Egg', prenom: 'Aurore', nom: 'Barrillon', groupe: 'Groupe 6' },
  { agence: 'Equatour', prenom: 'Isis', nom: 'Zahid', groupe: 'Groupe 5' },
  {
    agence: 'Event Success',
    prenom: 'Béatrice',
    nom: 'Bellanger',
    groupe: 'Groupe 6',
  },
  {
    agence: 'Event Success',
    prenom: 'Julie',
    nom: 'Aplincourt',
    groupe: 'Groupe 7',
  },
  {
    agence: 'Force Rose',
    prenom: 'Justine',
    nom: 'Dejoulx',
    groupe: 'Groupe 6',
  },
  {
    agence: 'Force Rose',
    prenom: 'Alexis',
    nom: 'Leroy',
    groupe: 'Groupe 7',
  },
  {
    agence: 'Freelance',
    prenom: 'Valérie',
    nom: 'Prost Gidon',
    groupe: 'Groupe 6',
  },
  {
    agence: 'Hopscotch',
    prenom: 'Marie',
    nom: 'Foucault',
    groupe: 'Groupe 7',
  },
  {
    agence: 'Imagine & Sens',
    prenom: 'Prune',
    nom: 'Perrissin Fabert',
    groupe: 'Groupe 7',
  },
  {
    agence: 'Imagine & Sens',
    prenom: 'Paul',
    nom: 'El Chabrawi',
    groupe: 'Groupe 8',
  },
  {
    agence: 'Instant Gravé',
    prenom: 'Céline',
    nom: 'Dos Santos',
    groupe: 'Groupe 8',
  },
  {
    agence: "It's a wrap",
    prenom: 'Diane',
    nom: 'Lopez de Arias',
    groupe: 'Groupe 1',
  },
  {
    agence: 'Joubert Voyages',
    prenom: 'Sophie',
    nom: 'Bastard',
    groupe: 'Groupe 8',
  },
  {
    agence: 'Kuoni Travel Lab',
    prenom: 'Delphine',
    nom: 'Morteau Varoqui',
    groupe: 'Groupe 17',
  },
  {
    agence: 'Samira',
    prenom: 'Samira',
    nom: 'Nouri',
    groupe: 'Groupe 9',
  },
  {
    agence: 'Kuoni Travel Lab',
    prenom: 'Marie-Odile',
    nom: 'Fleury',
    groupe: 'Groupe 9',
  },
  {
    agence: 'La Compagnie des Continents',
    prenom: 'Brinda',
    nom: 'Paul',
    groupe: 'Groupe 9',
  },
  {
    agence: 'Le Monde en direct',
    prenom: 'Aïcha',
    nom: 'Ahamed',
    groupe: 'Groupe 9',
  },
  {
    agence: 'Le Monde en direct',
    prenom: 'Emilie',
    nom: "Rogues de Fursac-L'hôte",
    groupe: 'Groupe 11',
  },
  {
    agence: 'Lever de Rideau',
    prenom: 'Laure',
    nom: 'Dupont-Hury',
    groupe: 'Groupe 10',
  },
  {
    agence: 'Madiba',
    prenom: 'Antoine',
    nom: 'Thorel',
    groupe: 'Groupe 10',
  },
  {
    agence: 'Make My Events',
    prenom: 'Virgine',
    nom: 'Peneau',
    groupe: 'Groupe 10',
  },
  {
    agence: "Maman l'agence",
    prenom: 'Laurence',
    nom: 'Boulay',
    groupe: 'Groupe 10',
  },
  {
    agence: "Maman l'agence",
    prenom: 'Bianca',
    nom: 'Bonvoisin',
    groupe: 'Groupe 11',
  },
  {
    agence: 'Missions MMM',
    prenom: 'Elisa',
    nom: 'Servières',
    groupe: 'Groupe 11',
  },
  {
    agence: 'Moma Events',
    prenom: 'Alexandra',
    nom: 'Leclerc',
    groupe: 'Groupe 12',
  },
  {
    agence: 'Moma Events',
    prenom: 'Thierry',
    nom: 'Ferreira',
    groupe: 'Groupe 17',
  },
  {
    agence: "Motiv'events",
    prenom: 'Analia',
    nom: 'Theillaud',
    groupe: 'Groupe 11',
  },
  {
    agence: "Motiv'events",
    prenom: 'Marie-Charlotte',
    nom: 'Fourticq-Collinot',
    groupe: 'Groupe 12',
  },
  { agence: 'MTC', prenom: 'Hélène', nom: 'Renimel', groupe: 'Groupe 16' },
  {
    agence: 'One Touch Travel',
    prenom: 'Arnaud',
    nom: 'Baudouin',
    groupe: 'Groupe 12',
  },
  {
    agence: 'Oohlala Events',
    prenom: 'Pascale',
    nom: 'Le Borgne',
    groupe: 'Groupe 12',
  },
  {
    agence: 'Peppermint',
    prenom: 'Christelle',
    nom: 'Gravier',
    groupe: 'Groupe 13',
  },
  {
    agence: 'Revents',
    prenom: 'Joris',
    nom: 'Rastello',
    groupe: 'Groupe 13',
  },
  {
    agence: 'Revents',
    prenom: 'Sylvain',
    nom: 'Champon',
    groupe: 'Groupe 18',
  },
  {
    agence: 'Sagarmatha',
    prenom: 'Sylviane',
    nom: 'Girardo',
    groupe: 'Groupe 17',
  },
  {
    agence: 'Sanbao Events',
    prenom: 'Marion',
    nom: 'Vignes',
    groupe: 'Groupe 13',
  },
  {
    agence: "S'cape Events",
    prenom: 'Valérie',
    nom: 'Beillard-Mottard',
    groupe: 'Groupe 14',
  },
  {
    agence: "S'cape Events",
    prenom: 'Robin',
    nom: 'Marchesseau',
    groupe: 'Groupe 15',
  },
  {
    agence: 'Scoop Voyages',
    prenom: 'Samuel',
    nom: 'Régnier',
    groupe: 'Groupe 8',
  },
  {
    agence: 'Somerset',
    prenom: 'Marine',
    nom: 'Le Goff',
    groupe: 'Groupe 14',
  },
  {
    agence: 'Somerset',
    prenom: 'Magalie',
    nom: 'Caizergues',
    groupe: 'Groupe 15',
  },
  {
    agence: 'SPC consulting',
    prenom: 'Sarah',
    nom: 'Pouzoulet',
    groupe: 'Groupe 15',
  },
  {
    agence: 'Succès des Stim',
    prenom: 'Mélanie',
    nom: 'Robier',
    groupe: 'Groupe 14',
  },
  {
    agence: 'Succès des Stim',
    prenom: 'Amélie',
    nom: 'Martin',
    groupe: 'Groupe 15',
  },
  {
    agence: 'Tupaia',
    prenom: 'Noémie',
    nom: 'Giraud Pons',
    groupe: 'Groupe 14',
  },
  {
    agence: 'Vatéa',
    prenom: 'Bénédicte',
    nom: 'Rivain',
    groupe: 'Groupe 16',
  },
  {
    agence: 'Vogue agence',
    prenom: 'Agnès',
    nom: 'Garcia',
    groupe: 'Groupe 18',
  },
  {
    agence: 'Voyel',
    prenom: 'Armelle',
    nom: 'Charliot Martineau',
    groupe: 'Groupe 16',
  },
  {
    agence: 'Wagram & Vous',
    prenom: 'Morgane',
    nom: 'Caubet',
    groupe: 'Groupe 16',
  },
  {
    agence: 'WMH Project Paris',
    prenom: 'Isabelle',
    nom: 'Gauttron',
    groupe: 'Groupe 4',
  },
  {
    agence: 'WMH Project Paris',
    prenom: 'Catherine',
    nom: 'Molins',
    groupe: 'Groupe 17',
  },
  {
    agence: 'XXL Happyness',
    prenom: 'Cindy',
    nom: 'Dauvin',
    groupe: 'Groupe 13',
  },
  {
    agence: 'XXL Happyness',
    prenom: 'Anne-Laure',
    nom: 'Bourgeon',
    groupe: 'Groupe 18',
  },
  {
    agence: 'Yellow Wings',
    prenom: 'Valérie',
    nom: 'Berger',
    groupe: 'Groupe 18',
  },
];

export const WorkshopGroup = [
  'Liste Alpha',
  'Groupe 1',
  'Groupe 2',
  'Groupe 3',
  'Groupe 4',
  'Groupe 5',
  'Groupe 6',
  'Groupe 7',
  'Groupe 8',
  'Groupe 9',
  'Groupe 10',
  'Groupe 11',
  'Groupe 12',
  'Groupe 13',
  'Groupe 14',
  'Groupe 15',
  'Groupe 16',
  'Groupe 17',
  'Groupe 18',
];

export const WorkshopEvents = [
  {
    groupe: 'Groupe 1',
    programme: {
      '14h00': '7th Sense',
      '14h15': 'Off Road',
      '14h30': 'BBN',
      '14h45': 'Qatar Airways',
      '15h00': 'Hilton Maurice',
      '15h15': 'Saudi Tourism Auhority',
      '15h30': 'Emacarena',
      '15h45': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '16h00': 'Emotions',
      '16h15': 'Sun Life',
      '16h30': 'KTI',
      '16h45': 'Victor',
      '17h00': 'MICE Assurance',
      '17h15': 'Avantgarde',
      '17h30': 'Dubaï Business  Events',
    },
  },
  {
    groupe: 'Groupe 2',
    programme: {
      '14h00': 'Abu Dhabi Convention & Exhibition bureau',
      '14h15': "Origin'Africa Events",
      '14h30': 'Beachcomber Resorts & Hotels',
      '14h45': 'Qincentive',
      '15h00': 'Dorak ',
      '15h15': 'Shangri-la',
      '15h30': 'Emirates',
      '15h45': '7th Sense',
      '16h00': 'Incent India',
      '16h15': "Terre d'Ailleurs",
      '16h30': 'Mauritius Tourism Promotion Authority',
      '16h45': 'Merity Incoming',
      '17h00': 'Off Road',
      '17h15': 'BBN',
      '17h30': 'Qatar Airways',
    },
  },
  {
    groupe: 'Groupe 3',
    programme: {
      '14h00': 'Avantgarde',
      '14h15': 'Dubaï Business  Events',
      '14h30': 'Blue Island Seychelles',
      '14h45': 'Sassy Events',
      '15h00': 'Easia',
      '15h15': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '15h30': 'Emotions',
      '15h45': 'Abu Dhabi Convention & Exhibition bureau',
      '16h00': 'Incentivos Ibiza',
      '16h15': 'Tucaya',
      '16h30': 'Merity Incoming',
      '16h45': '7th Sense',
      '17h00': "Origin'Africa Events",
      '17h15': 'Beachcomber Resorts & Hotels',
      '17h30': 'Qincentive',
    },
  },
  {
    groupe: 'Groupe 4',
    programme: {
      '14h00': 'BBN',
      '14h15': 'Qatar Airways',
      '14h30': 'Hilton Maurice',
      '14h45': 'Saudi Tourism Auhority',
      '15h00': 'Emacarena',
      '15h15': 'Spice Egypte',
      '15h30': 'Incent India',
      '15h45': 'Avantgarde',
      '16h00': 'KTI',
      '16h15': 'Victor',
      '16h30': 'MICE Assurance',
      '16h45': 'Abu Dhabi Convention & Exhibition bureau',
      '17h00': 'Dubaï Business  Events',
      '17h15': 'Blue Island Seychelles',
      '17h30': 'Sassy Events',
    },
  },
  {
    groupe: 'Groupe 5',
    programme: {
      '14h00': 'Beachcomber Resorts & Hotels',
      '14h15': 'Qincentive',
      '14h30': 'Dorak ',
      '14h45': 'Shangri-la',
      '15h00': 'Emirates',
      '15h15': "Step'In",
      '15h30': 'Incentivos Ibiza',
      '15h45': 'BBN',
      '16h00': 'Mauritius Tourism Promotion Authority',
      '16h15': '7th Sense',
      '16h30': 'Off Road',
      '16h45': 'Avantgarde',
      '17h00': 'Qatar Airways',
      '17h15': 'Hilton Maurice',
      '17h30': 'Saudi Tourism Auhority',
    },
  },
  {
    groupe: 'Groupe 6',
    programme: {
      '14h00': 'Blue Island Seychelles',
      '14h15': 'Sassy Events',
      '14h30': 'Easia',
      '14h45': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '15h00': 'Emotions',
      '15h15': 'Sun Life',
      '15h30': 'KTI',
      '15h45': 'Beachcomber Resorts & Hotels',
      '16h00': 'Merity Incoming',
      '16h15': 'Abu Dhabi Convention & Exhibition bureau',
      '16h30': "Origin'Africa Events",
      '16h45': 'BBN',
      '17h00': 'Qincentive',
      '17h15': 'Dorak ',
      '17h30': 'Shangri-la',
    },
  },
  {
    groupe: 'Groupe 7',
    programme: {
      '14h00': 'Hilton Maurice',
      '14h15': 'Saudi Tourism Auhority',
      '14h30': 'Emacarena',
      '14h45': 'Spice Egypte',
      '15h00': 'Incent India',
      '15h15': "Terre d'Ailleurs",
      '15h30': 'Mauritius Tourism Promotion Authority',
      '15h45': 'Blue Island Seychelles',
      '16h00': 'MICE Assurance',
      '16h15': 'Avantgarde',
      '16h30': 'Dubaï Business  Events',
      '16h45': 'Beachcomber Resorts & Hotels',
      '17h00': 'Sassy Events',
      '17h15': 'Easia',
      '17h30': 'Spice Emirats, Jordanie, Géorgie & Portugal',
    },
  },
  {
    groupe: 'Groupe 8',
    programme: {
      '14h00': 'Dorak ',
      '14h15': 'Shangri-la',
      '14h30': 'Emirates',
      '14h45': "Step'In",
      '15h00': 'Incentivos Ibiza',
      '15h15': 'Tucaya',
      '15h30': 'Merity Incoming',
      '15h45': 'Hilton Maurice',
      '16h00': 'Off Road',
      '16h15': 'BBN',
      '16h30': 'Qatar Airways',
      '16h45': 'Blue Island Seychelles',
      '17h00': 'Saudi Tourism Auhority',
      '17h15': 'Emacarena',
      '17h30': 'Spice Egypte',
    },
  },
  {
    groupe: 'Groupe 9',
    programme: {
      '14h00': 'Easia',
      '14h15': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '14h30': 'Emotions',
      '14h45': 'Sun Life',
      '15h00': 'KTI',
      '15h15': 'Victor',
      '15h30': 'MICE Assurance',
      '15h45': 'Dorak ',
      '16h00': "Origin'Africa Events",
      '16h15': 'Beachcomber Resorts & Hotels',
      '16h30': 'Qincentive',
      '16h45': 'Hilton Maurice',
      '17h00': 'Shangri-la',
      '17h15': 'Emirates',
      '17h30': "Step'In",
    },
  },
  {
    groupe: 'Groupe 10',
    programme: {
      '14h00': 'Emacarena',
      '14h15': 'Spice Egypte',
      '14h30': 'Incent India',
      '14h45': "Terre d'Ailleurs",
      '15h00': 'Mauritius Tourism Promotion Authority',
      '15h15': '7th Sense',
      '15h30': 'Off Road',
      '15h45': 'Easia',
      '16h00': 'Dubaï Business  Events',
      '16h15': 'Blue Island Seychelles',
      '16h30': 'Sassy Events',
      '16h45': 'Dorak ',
      '17h00': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '17h15': 'Emotions',
      '17h30': 'Sun Life',
    },
  },
  {
    groupe: 'Groupe 11',
    programme: {
      '14h00': 'Emirates',
      '14h15': "Step'In",
      '14h30': 'Incentivos Ibiza',
      '14h45': 'Tucaya',
      '15h00': 'Merity Incoming',
      '15h15': 'Abu Dhabi Convention & Exhibition bureau',
      '15h30': "Origin'Africa Events",
      '15h45': 'Emacarena',
      '16h00': 'Qatar Airways',
      '16h15': 'Hilton Maurice',
      '16h30': 'Saudi Tourism Auhority',
      '16h45': 'Easia',
      '17h00': 'Spice Egypte',
      '17h15': 'Incent India',
      '17h30': "Terre d'Ailleurs",
    },
  },
  {
    groupe: 'Groupe 12',
    programme: {
      '14h00': 'Emotions',
      '14h15': 'Sun Life',
      '14h30': 'KTI',
      '14h45': 'Victor',
      '15h00': 'MICE Assurance',
      '15h15': 'Avantgarde',
      '15h30': 'Dubaï Business  Events',
      '15h45': 'Emirates',
      '16h00': 'Qincentive',
      '16h15': 'Dorak ',
      '16h30': 'Shangri-la',
      '16h45': 'Emacarena',
      '17h00': 'Step\In',
      '17h15': 'Incentivos Ibiza',
      '17h30': 'Tucaya',
    },
  },
  {
    groupe: 'Groupe 13',
    programme: {
      '14h00': 'Incent India',
      '14h15': "Terre d'Ailleurs",
      '14h30': 'Mauritius Tourism Promotion Authority',
      '14h45': '7th Sense',
      '15h00': 'Off Road',
      '15h15': 'BBN',
      '15h30': 'Qatar Airways',
      '15h45': 'Spice Egypte',
      '16h00': 'Sassy Events',
      '16h15': 'Easia',
      '16h30': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '16h45': 'Emirates',
      '17h00': 'Sun Life',
      '17h15': 'KTI',
      '17h30': 'Victor',
    },
  },
  {
    groupe: 'Groupe 14',
    programme: {
      '14h00': 'Incentivos Ibiza',
      '14h15': 'Tucaya',
      '14h30': 'Merity Incoming',
      '14h45': 'Abu Dhabi Convention & Exhibition bureau',
      '15h00': 'Origin\Africa Events',
      '15h15': 'Beachcomber Resorts & Hotels',
      '15h30': 'Qincentive',
      '15h45': 'Step\In',
      '16h00': 'Saudi Tourism Auhority',
      '16h15': 'Emacarena',
      '16h30': 'Spice Egypte',
      '16h45': 'Emotions',
      '17h00': 'Terre d\Ailleurs',
      '17h15': 'Mauritius Tourism Promotion Authority',
      '17h30': '7th Sense',
    },
  },
  {
    groupe: 'Groupe 15',
    programme: {
      '14h00': 'KTI',
      '14h15': 'Victor',
      '14h30': 'MICE Assurance',
      '14h45': 'Avantgarde',
      '15h00': 'Dubaï Business  Events',
      '15h15': 'Blue Island Seychelles',
      '15h30': 'Sassy Events',
      '15h45': 'Sun Life',
      '16h00': 'Shangri-la',
      '16h15': 'Emirates',
      '16h30': "Step'In",
      '16h45': 'Incent India',
      '17h00': 'Tucaya',
      '17h15': 'Merity Incoming',
      '17h30': 'Abu Dhabi Convention & Exhibition bureau',
    },
  },
  {
    groupe: 'Groupe 16',
    programme: {
      '14h00': 'Mauritius Tourism Promotion Authority',
      '14h15': '7th Sense',
      '14h30': 'Off Road',
      '14h45': 'BBN',
      '15h00': 'Qatar Airways',
      '15h15': 'Hilton Maurice',
      '15h30': 'Saudi Tourism Auhority',
      '15h45': "Terre d'Ailleurs",
      '16h00': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '16h15': 'Emotions',
      '16h30': 'Sun Life',
      '16h45': 'Incentivos Ibiza',
      '17h00': 'Victor',
      '17h15': 'MICE Assurance',
      '17h30': 'Avantgarde',
    },
  },
  {
    groupe: 'Groupe 17',
    programme: {
      '14h00': 'Merity Incoming',
      '14h15': 'Abu Dhabi Convention & Exhibition bureau',
      '14h30': "Origin'Africa Events",
      '14h45': 'Beachcomber Resorts & Hotels',
      '15h00': 'Qincentive',
      '15h15': 'Dorak ',
      '15h30': 'Shangri-la',
      '15h45': 'Tucaya',
      '16h00': 'Spice Egypte',
      '16h15': 'Incent India',
      '16h30': "Terre d'Ailleurs",
      '16h45': 'KTI',
      '17h00': '7th Sense',
      '17h15': 'Off Road',
      '17h30': 'BBN',
    },
  },
  {
    groupe: 'Groupe 18',
    programme: {
      '14h00': 'MICE Assurance',
      '14h15': 'Avantgarde',
      '14h30': 'Dubaï Business  Events',
      '14h45': 'Blue Island Seychelles',
      '15h00': 'Sassy Events',
      '15h15': 'Easia',
      '15h30': 'Spice Emirats, Jordanie, Géorgie & Portugal',
      '15h45': 'Victor',
      '16h00': "Step'In",
      '16h15': 'Incentivos Ibiza',
      '16h30': 'Tucaya',
      '16h45': 'Mauritius Tourism Promotion Authority',
      '17h00': 'Abu Dhabi Convention & Exhibition bureau',
      '17h15': "Origin'Africa Events",
      '17h30': 'Beachcomber Resorts & Hotels',
    },
  },
];
